# INTRO TO JUPYTER NOTEBOOK

In [6]:
# 1. CMD
# 2. jupyter notebook > this service/ widow should always be running
# 3. default location > http://localhost:8888/tree
# 4. / means C:\ is root Folder
# 5. Create a new Python file

In [7]:
# 9324387590

# INTRO TO NUMPY

In [9]:
# https://numpy.org/doc/stable/user/quickstart.html#an-example

##WHY NUMPY ???

In [11]:
a1 = [1,2,3,4,5,6,7,8,9]
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
#  to double the elements in the list a1
for i in a1:
    print(i*2)

2
4
6
8
10
12
14
16
18


In [15]:
a2 = [i*2 for i in a1] #list comprehension
print(a2)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
#  to square the elements in the list a1

In [17]:
print(a1)
for i in a1:
    print(i**2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
1
4
9
16
25
36
49
64
81


In [19]:
a3 = [i**2 for i in a1]
print(a3)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


## better approach ???

In [21]:
import numpy as np

In [22]:
print("hello world")

hello world


In [23]:
name  = "Rakesh"
print(name.casefold())

rakesh


In [24]:
arr1 = np.array(a1)

In [25]:
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [26]:
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [27]:
a1*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
print(arr1*2)# numpy supports elemntwise operation 

[ 2  4  6  8 10 12 14 16 18]


In [29]:
print(arr1**3)

[  1   8  27  64 125 216 343 512 729]
