#  Creating 1D Array


In [1]:
import numpy as np

In [2]:
# using arange()

In [17]:
arr1 = np.arange(5,51,5)

In [16]:
arr1

array([], dtype=int32)

In [19]:
arr1 = np.arange(10) #default start will be ZERO
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr1 = np.arange(15,200) 
arr1

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
       184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 19

In [21]:
arr1 = np.arange(15,200,5) #last value in not included
arr1

array([ 15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
        80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140,
       145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])

In [23]:
arr1 = np.arange(15,200,-5) # will not work
arr1

array([], dtype=int32)

In [25]:
arr1 = np.arange(200,-200,-5) # will   work  for  np.arange(pos,neg,neg)
arr1

array([ 200,  195,  190,  185,  180,  175,  170,  165,  160,  155,  150,
        145,  140,  135,  130,  125,  120,  115,  110,  105,  100,   95,
         90,   85,   80,   75,   70,   65,   60,   55,   50,   45,   40,
         35,   30,   25,   20,   15,   10,    5,    0,   -5,  -10,  -15,
        -20,  -25,  -30,  -35,  -40,  -45,  -50,  -55,  -60,  -65,  -70,
        -75,  -80,  -85,  -90,  -95, -100, -105, -110, -115, -120, -125,
       -130, -135, -140, -145, -150, -155, -160, -165, -170, -175, -180,
       -185, -190, -195])

In [26]:
arr1 = np.arange(10,100,0.5) # fraction step size is supported in arange , but not in range()
arr1

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5,
       32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. ,
       37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5,
       43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. ,
       48.5, 49. , 49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5,
       54. , 54.5, 55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. ,
       59.5, 60. , 60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5,
       65. , 65.5, 66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. ,
       70.5, 71. , 71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75. , 75.5,
       76. , 76.5, 77. , 77.5, 78. , 78.5, 79. , 79.5, 80. , 80.5, 81. ,
       81.5, 82. , 82.5, 83. , 83.5, 84. , 84.5, 85

In [3]:
# checking the Attributes

In [27]:
arr1.shape

(180,)

In [28]:
arr1.size

180

In [29]:
arr1.ndim

1

# Creating 2D Array

In [4]:
#  using list of lists

In [31]:
m = [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]

In [32]:
print(type(m))

<class 'list'>


In [33]:
m

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

In [34]:
m_arr = np.array(m)

In [35]:
m_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [36]:
type(m_arr)

numpy.ndarray

In [6]:
# checking the Attributes

In [37]:
m_arr.ndim

2

In [38]:
m_arr.shape #

(2, 12)

In [39]:
m_arr.size #this will always be a Integer , count of elements

24

In [41]:
z = [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]

In [42]:
arr4 = np.array(z)

In [43]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [44]:
arr4.ndim

2

In [45]:
arr4.shape

(3, 12)

In [46]:
arr4.size

36

In [7]:
# using reshape() to change the array from 1D to 2D
#  can also be changed to higher Dimensions

In [47]:
arr5 = np.arange(12)

In [48]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
arr5.ndim

1

In [50]:
arr5.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
arr5.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
arr5.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
arr5.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [56]:
arr5.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [57]:
arr5.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [58]:
arr5.reshape(12,2) # rows*col = array size

ValueError: cannot reshape array of size 12 into shape (12,2)

In [59]:
arr5.reshape(3,3) # rows*col = array size

ValueError: cannot reshape array of size 12 into shape (3,3)

In [8]:
# using linspace() to change the array from 1D to 2D

In [61]:
arr6 =  np.linspace(1,10,15).reshape(3,5)

In [62]:
arr6

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [9]:
# checking the Attributes

In [63]:
arr6.ndim

2

In [64]:
arr6.shape

(3, 5)

In [65]:
arr6.size

15

In [10]:
# 1D will have one [] 
# 2d will have [[ ]]
# 3d will have [[[ ]]]
# thus by counting the opening square brackets we can clerly identify the Dimanesion of array