# indexing and Slicing

#  with 1d array

In [1]:
import numpy as np

In [6]:
arr1 = np.arange(5,12)
arr1

array([ 5,  6,  7,  8,  9, 10, 11])

In [7]:
arr1[0]

5

In [9]:
arr1[5]

10

In [11]:
# slicing
arr1[0:3]

array([5, 6, 7])

In [12]:
arr1[0:6:2]

array([5, 7, 9])

In [13]:
arr1[0:6:3]

array([5, 8])

In [14]:
# supports negative indexing
arr1[-1]

11

In [15]:
# array reversal using negative indexing
#  reversal in based on index position
arr1[::-1]

array([11, 10,  9,  8,  7,  6,  5])

# with 2d arrays

In [19]:
arr2 = np.arange(15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
arr2.ndim

2

In [21]:
arr2[0] #array[row_number_start:row_number_end]

array([0, 1, 2, 3, 4])

In [22]:
arr2[1]

array([5, 6, 7, 8, 9])

In [24]:
arr2[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [26]:
arr4[0]

array([0, 1, 2, 3, 4])

In [27]:
arr4[3]

array([15, 16, 17, 18, 19])

In [28]:
arr4[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
arr4[0:5:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Slicing

In [2]:
 # arr1[x][y] #arry[rows][column]

In [33]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
arr4[0][0]

0

In [37]:
arr4[2][2]

12

In [41]:
arr4[4:6][1:3]
# arr4[4:6]

array([[25, 26, 27, 28, 29]])

In [ ]:
# for intersection of   rows and columns 
# arr1[x][y] 
#arry[rows_start:rows_end,column_start:column_end]

In [42]:
arr4[4:6,1:3]

array([[21, 22],
       [26, 27]])

# Indexing with Boolean arrays

In [3]:
# masking
#  boolean Indecing

# Universal function

In [4]:
# /HW
1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


1. 'Priya', 'Rohit', 'Aryan'
2. 'Riya','Devanshi'
3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
4. 'Avni'
5. 'Neha'

2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35

SyntaxError: invalid syntax (3487268980.py, line 8)

In [ ]:
score = np.random.randint(10,100,15).reshape(5,3)
# 1. find all scores > 50
# 2. find all scores <35


In [ ]:
score