In [1]:
import numpy as np

# Indexing with Boolean arrays

In [4]:
# masking
# boolean Indecing

In [5]:
arr1 = np.arange(12).reshape(3,4)

In [6]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr1 + 10 #this is elementwise operation

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [8]:
arr1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [9]:
arr1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
arr1<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [11]:
arr1 % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [12]:
arr1 % 2 != 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [13]:
arr1 % 3 == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [14]:
# multiple conditions

In [15]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# arr1 % 2 == 0
# and 
# arr1 % 3 == 0


In [16]:
(arr1 % 2 == 0) & (arr1 % 3 == 0)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [17]:
# arr1 % 2 == 0
# or
# arr1 % 3 == 0

In [20]:
arr2 = (arr1 % 2 == 0) | (arr1 % 3 == 0)

In [19]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr2 #boolean aary ? values are boolean 

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [22]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [23]:
arr1[arr1>10]

array([11])

In [24]:
arr1[arr1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [25]:
arr1[(arr1 % 2 == 0) & (arr1 % 3 == 0)]

array([0, 6])

# Universal function

In [ ]:
# arrays must be of same shape and size

In [26]:
# https://numpy.org/doc/stable/user/quickstart.html#universal-functions

In [27]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [28]:
a + 10

array([21, 32, 43, 54, 65])

In [29]:
a

array([11, 22, 33, 44, 55])

In [30]:
a + b

array([12, 24, 36, 48, 60])

In [31]:
a- b

array([10, 20, 30, 40, 50])

In [32]:
a*b

array([ 11,  44,  99, 176, 275])

In [33]:
a/b

array([11., 11., 11., 11., 11.])

In [34]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 0]


In [35]:
a*b

array([ 11,  44,  99, 176,   0])

In [36]:
a/b

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_25216\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([11., 11., 11., 11., inf])

In [ ]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,0])
print(a)
print(b)

In [37]:
b/a

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.        ])

In [ ]:
a = np.array([11,22,33,44,0])
b = np.array([1,2,3,4,0])
print(a)
print(b)

In [38]:
a/b

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_25216\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([11., 11., 11., 11., inf])

In [39]:
a = np.array([11,22,33,44])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44]
[1 2 3 4 5]


In [40]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [ ]:
# https://numpy.org/doc/stable/user/quickstart.html#broadcasting-rules

In [55]:
# /HW
# 1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


# 1. 'Priya', 'Rohit', 'Aryan'
# 2. 'Riya','Devanshi'
# 3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
# 4. 'Avni'
# 5. 'Neha'

# 2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
# 1. find all scores > 50
# 2. find all scores <35

In [56]:
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [57]:
score

array([[65, 34, 78],
       [70, 95, 68],
       [67, 82, 44],
       [48, 43, 32],
       [25, 43, 44]])

In [58]:
score[score>50]

array([65, 78, 70, 95, 68, 67, 82])

In [ ]:
score = np.random.randint(10,100,15).reshape(5,3)
# 1. find all scores > 50
# 2. find all scores <35


In [ ]:
score

In [71]:
np.random.randint(10,100,15).reshape(5,3)

array([[72, 37, 33],
       [92, 17, 67],
       [70, 74, 88],
       [12, 54, 11],
       [11, 97, 78]])