# Aggregate Function

In [14]:
# 1D array

In [1]:
import numpy as np

In [2]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b) 

[11 22 33 44 55]
[1 2 3 4 5]


In [3]:
a + b

array([12, 24, 36, 48, 60])

In [4]:
a * b 

array([ 11,  44,  99, 176, 275])

In [7]:
np.sum(a)

165

In [8]:
np.min(a)

11

In [9]:
np.min(b)

1

In [10]:
np.max(a)

55

In [11]:
np.max(b)

5

In [12]:
np.mean(a)

33.0

In [13]:
np.mean(b)

3.0

In [15]:
# 2D array

In [18]:
len(np.arange(10,60,2))

25

In [19]:
arr1 = np.arange(10,60,2).reshape(5,5)

In [20]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [22]:
np.sum(arr1,axis=None)

850

In [23]:
np.sum(arr1,axis=0) #sum of columns

array([150, 160, 170, 180, 190])

In [25]:
np.sum(arr1,axis=1) #sum of rows

array([ 70, 120, 170, 220, 270])

In [26]:
np.max(arr1)

58

In [28]:
np.max(arr1,axis=1)

array([18, 28, 38, 48, 58])

In [29]:
np.max(arr1,axis=0)

array([50, 52, 54, 56, 58])

In [30]:
np.mean(arr1,axis=1)

array([14., 24., 34., 44., 54.])

In [31]:
score = np.random.randint(10,100,15).reshape(5,3)

In [32]:
score

array([[71, 96, 67],
       [36, 87, 70],
       [85, 26, 24],
       [84, 44, 55],
       [31, 75, 90]])

In [33]:
np.sum(score,axis=0) #col

array([307, 328, 306])

In [34]:
np.sum(score,axis=1) #rows

array([234, 193, 135, 183, 196])

In [35]:
np.mean(score,axis=1)

array([78.        , 64.33333333, 45.        , 61.        , 65.33333333])

In [36]:
np.min(score,axis=1)

array([67, 36, 24, 44, 31])

In [37]:
np.max(score,axis=0)

array([85, 96, 90])

# Logical Functions

In [ ]:
# any :  all the elemets should be zero for o/p to be False : behaves like OR
# all : all the elemets should be non-zero for o/p to be True : behaves like AND
# True and False

In [38]:
score = np.random.randint(10,100,15).reshape(5,3)

In [39]:
score

array([[54, 80, 48],
       [15, 88, 83],
       [24, 90, 11],
       [55, 92, 29],
       [57, 70, 49]])

In [40]:
arr5 = np.array([11,22,33,0,55])
np.any(arr5)

True

In [41]:
arr5 = np.array([0,0,0,0,0,55])
np.any(arr5)

True

In [44]:
arr5 = np.array([0,0,0,0,0,0])
np.any(arr5)

False

In [ ]:
# all

In [45]:
arr5 = np.array([11,22,33,0,55])
np.all(arr5)

False

In [46]:
arr5 = np.array([11,22,33,55])
np.all(arr5)

True

In [ ]:
# https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting