In [1]:
import numpy as np

In [2]:
data = np.loadtxt('fitbit.txt',dtype='str')

In [3]:
# numpy array is ?
#  a. Homogenous array
#  b . Hetrogenous array


# List is Hetrogenous
# numpy array is Homogenous

In [4]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [5]:
print(type(data))

<class 'numpy.ndarray'>


In [6]:
data.ndim

2

In [7]:
data.shape #rows : 26 and coln : 7

(26, 7)

In [8]:
data.size

182

In [9]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [10]:
data[1]

array(['07-10-2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

# Data Cleaning

In [11]:
# data has no header
# all data is in STRING type

In [12]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [13]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [14]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [15]:
data.T[1]

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [16]:
tup_1 = (11,22,33,44) #packing a tuple
print(tup_1[0])
print(tup_1[1])
print(tup_1[2])

11
22
33


In [17]:
a,b,c,d=tup_1 #unpacking a tuple
print(a)
print(b)

11
22


In [18]:
date ,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg=data.T

In [19]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [20]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

# Data types in Numpy

In [21]:
# https://numpy.org/doc/stable/user/basics.types.html

In [22]:
step_count.dtype

dtype('<U10')

In [30]:
type(step_count)

numpy.ndarray

In [23]:
# changing the string data type to 'int'

In [24]:
step_count = np.array(step_count,dtype='int')

In [25]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [26]:
step_count.dtype

dtype('int32')

In [27]:
# changing the   data types of other parameters to 'int'

In [32]:
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
weight_kg = np.array(weight_kg,dtype='int')

In [33]:
calories_burned

array([181, 208, 341, 190, 307, 302, 198, 201, 195, 327, 331, 318, 344,
       204, 180, 201, 329, 315, 197, 184, 328, 322, 327, 148, 235, 184])

In [34]:
calories_burned.dtype

dtype('int32')

In [35]:
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [36]:
hours_of_sleep.dtype

dtype('int32')

In [37]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [38]:
weight_kg.dtype

dtype('int32')

In [28]:
# focussing on 'mood' data
# data is in numerical form but is repetative
# checking the pattern of data 

In [39]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [40]:
# mood data is categorical

In [29]:
# 100 = sad
# 200 =  neutral
# 300 = happy

In [41]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [42]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [49]:
mood == '100' # 100 = sad
mood[mood == '100'] = 'sad'

In [47]:
mood == '200' # 200 =  neutral
mood[mood == '200'] = 'neutral'

In [48]:
mood == '300' # 300 = happy
mood[mood == '300'] = 'happy'

In [50]:
mood

array(['neutral', 'neutral', 'happy', 'sad', 'happy', 'happy', 'sad',
       'neutral', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'neutral', 'neutral', 'neutral', 'happy', 'happy', 'sad', 'sad',
       'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral'],
      dtype='<U10')

# Analysing data